# Generated by Django 5.1.5 on 2026-09-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academics.grado')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='labs.laboratorio')),
            ],
            options={
                'ordering': ['fecha_entrega', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('abierta', 'Respuesta abierta'), ('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero o falso')], default='abierta', max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('respuesta_correcta', models.CharField(blank=True, max_length=200)),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='assignments.actividad')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
