# Generated by Django 5.1.5 on 2026-09-02 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cuerpo', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/')),
                ('enlace', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagen', 'Imagen'), ('video', 'Video'), ('enlace', 'Enlace'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='content.contenido')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='academics.grado')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_asignados', to='content.modulo')),
            ],
            options={
                'ordering': ['orden', 'modulo__nombre'],
                'unique_together': {('modulo', 'grado')},
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='modulo_grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='content.modulogrado'),
        ),
    ]
