# Generated by Django 5.1.5 on 2026-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apodo',
            field=models.CharField(blank=True, max_length=30, verbose_name='apodo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(choices=[('🧑\u200d🎓', 'Estudiante'), ('🤖', 'Robot'), ('🐱', 'Gato'), ('🦊', 'Zorro'), ('🦉', 'Búho'), ('🐙', 'Pulpo'), ('🐲', 'Dragón'), ('👽', 'Alienígena'), ('🥷', 'Ninja'), ('🦄', 'Unicornio'), ('⚡', 'Rayo'), ('🚀', 'Cohete')], default='🧑\u200d🎓', max_length=10),
        ),
    ]
