# Generated by Django 5.1.5 on 2026-09-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academics.grado'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesorgrado',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grado'),
        ),
        migrations.AddField(
            model_name='profesorgrado',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='grados',
            field=models.ManyToManyField(blank=True, related_name='profesores', through='academics.ProfesorGrado', to='academics.grado'),
        ),
        migrations.AlterUniqueTogether(
            name='profesorgrado',
            unique_together={('profesor', 'grado')},
        ),
    ]
