# Generated by Django 5.1.5 on 2026-09-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas_actividad/%Y/%m/')),
                ('estado', models.CharField(choices=[('entregado', 'Entregado'), ('tarde', 'Entregado tarde'), ('revisado', 'Revisado')], default='entregado', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='assignments.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academics.estudiante')),
            ],
            options={
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='academics.profesor')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='submissions.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('es_correcta', models.BooleanField(blank=True, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='submissions.entrega')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='assignments.pregunta')),
            ],
            options={
                'unique_together': {('entrega', 'pregunta')},
            },
        ),
    ]
