# Generated by Django 5.1.5 on 2026-09-02 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('quiz', 'Cuestionario'), ('entrega_archivo', 'Entrega de archivo'), ('ensamble_pc', 'Ensamble de computador'), ('direccionamiento_ip', 'Direccionamiento IP'), ('editor_web', 'Editor HTML/CSS/JS'), ('simulador_bd', 'Simulador de base de datos')], max_length=30)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modulo_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='content.modulogrado')),
            ],
            options={
                'ordering': ['fecha_limite', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No iniciado'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='no_iniciado', max_length=20)),
                ('porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('datos_estado', models.JSONField(blank=True, default=dict)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='entregas_lab/%Y/%m/')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='academics.estudiante')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='labs.laboratorio')),
            ],
            options={
                'unique_together': {('estudiante', 'laboratorio')},
            },
        ),
    ]
